In [ ]:
# ! pip install tensorflow

In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.7.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


11501568/11490434 [==============================] - 0s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])


In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.16356291,  0.03340682, -0.31842664,  0.05424215, -0.76615155,
         0.5302319 ,  0.02511609,  0.15165251,  0.75775   , -0.10370134]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()


array([[0.10346141, 0.09083481, 0.06389295, 0.09274723, 0.04083274,
        0.14928657, 0.09008484, 0.10223646, 0.18742631, 0.07919668]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [7]:
loss_fn(y_train[:1], predictions).numpy()


1.9018875

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [9]:
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2958 - accuracy: 0.9137
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1452 - accuracy: 0.9565
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1089 - accuracy: 0.9672
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0874 - accuracy: 0.9722
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0757 - accuracy: 0.9764


In [10]:
model.evaluate(x_test,  y_test, verbose=2)


313/313 - 0s - loss: 0.0744 - accuracy: 0.9772 - 454ms/epoch - 1ms/step


[0.0744071826338768, 0.9771999716758728]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [12]:
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.07818687e-06, 9.63482183e-09, 4.47162938e-06, 1.38972930e-04,
        1.56515697e-12, 5.79238588e-07, 2.39523961e-12, 9.99839664e-01,
        4.90633283e-07, 1.46940611e-05],
       [1.32052929e-08, 8.64567526e-04, 9.99121726e-01, 1.09915063e-05,
        6.03194049e-14, 2.60151819e-06, 4.04383593e-09, 1.39261421e-12,
        1.17761495e-07, 1.69419546e-13],
       [2.64267032e-06, 9.98757839e-01, 7.55760630e-05, 2.35931166e-05,
        3.14164608e-05, 1.13522901e-06, 2.42847113e-06, 9.72102513e-04,
        1.31651585e-04, 1.57753198e-06],
       [9.99096394e-01, 1.99505905e-08, 8.47719493e-04, 3.50446612e-07,
        2.81192996e-07, 1.11895599e-06, 4.58963877e-05, 4.25379721e-06,
        1.50230198e-06, 2.60656566e-06],
       [1.13532769e-05, 9.91034987e-09, 5.21362927e-05, 2.82861561e-06,
        9.88871276e-01, 7.38865083e-07, 4.27608302e-06, 2.00453826e-04,
        1.48474537e-05, 1.08420039e-02]], dtype=float32)>